### ISSUE TITLE
Implement the payment gateway in Flutter for subscriptions.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2336]

**Comment by Uttkarsh-raj** [comment]
I did integrate the payment gateway but for it to authenticate the transactions for OWASP we would require the stripe secret key of the account which is not possible. So instead of that we would have to link the different tiers to the donation page options provided in the OWASP donation page and try to map these using js injection or just try to change the selected value from the app itself. After doing my research it was possible and was integrated in this pr https://github.com/OWASP-BLT/BLT-Flutter/pull/413 which i think solves this issue.

**Comment by Uttkarsh-raj** [comment]
@DonnieBLT I think we can close this because we went for a different approach.

**Comment by Uttkarsh-raj** [comment]
We modified this feature from a subscription to a donate feature and this was resolved in this pr.
https://github.com/OWASP-BLT/BLT-Flutter/pull/413
